# Arrays in Python

This notebook explores the concept of arrays in Python using the `array` module and NumPy. We'll cover definitions, basic operations, and typical use cases.

In [ ]:
# Importing the array module
import array

## Creating an Array using array module

In [ ]:
# 'i' is the typecode for signed integers
arr = array.array('i', [1, 2, 3, 4, 5])
print(arr)

array('i', [1, 2, 3, 4, 5])


## Accessing and modifying elements

In [ ]:
# iterating and printing each item
for i in range(len(arr)):
    print(arr[i], end=" ")

1 10 3 4 5 

In [ ]:
print(arr[0])      # Access first element
arr[1] = 20        # Modify second element
print(arr)

1
array('i', [1, 20, 3, 4, 5])


## Common methods

In [ ]:
arr.append(6)      # Add to end
arr.insert(2, 10)  # Insert at index 2
print(arr)

arr.pop()          # Remove last item
arr.remove(20)     # Remove specific value
print(arr)

array('i', [1, 20, 10, 3, 4, 5, 6])
array('i', [1, 10, 3, 4, 5])


# NumPy Arrays

For numerical and multidimensional data, we use NumPy arrays for better performance and features.

In [ ]:
import numpy as np

# Creating NumPy arrays
np_arr = np.array([1, 2, 3, 4, 5])
print(np_arr)

[1 2 3 4 5]


## NumPy operations

In [ ]:
# Vectorized operations
print(np_arr + 10)   # Add 10 to each element
print(np_arr * 2)    # Multiply each element by 2

# Slicing
print(np_arr[1:4])

[11 12 13 14 15]
[ 2  4  6  8 10]
[2 3 4]


## 2D Arrays with NumPy

In [ ]:
# Matrix representation
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

# Accessing elements
print(matrix[0][1])  # Element at 1st row, 2nd column

[[1 2]
 [3 4]]
2


# Summary

- Use `array.array()` when you need type-specific arrays.
- Use NumPy for advanced, efficient numerical computing.
- Arrays allow fast, index-based access and are useful in many DSA problems.